### ISSUE TITLE
Incorrect display of durability of items in containers

### ISSUE THREAD

**Issue by Lisici4** [psdKingybu/colourful-containers#1]
If the tool has a durabilty strip, then when the tool is in the container, this strip is cut off
![zDliAj28-P8](https://github.com/user-attachments/assets/6336c2a1-2810-4778-bdc5-4facdf2e94f7)
![I6TaMk4LUdk](https://github.com/user-attachments/assets/5ff64a30-4b9a-491a-8472-496b91a952be)

**Comment by psdKingybu** [comment]
If you play without optiGUI there is sadly no fix for this BUT it got fixed in 1.21.2 so if you play on the newest version that should be fixed. 
If you use OptiGUI/Optifine you can select the Modded language which also fixes this
![image](https://github.com/user-attachments/assets/7d5f0001-b64d-4e7a-b79a-9623064300fb)

**Comment by Lisici4** [comment]
Strange, I don’t have exactly these options in the settings. Hide GUI text didn't help the durability is still cut off
![image](https://github.com/user-attachments/assets/f167dc00-c01b-42f8-87cd-568cb1ae0ab5)

**Comment by Lisici4** [comment]
I figured it out, I had to select the Show GUI text option, now the durability is fully displayed. Thanks for help!

**Comment by psdKingybu** [comment]
Seems like you are not using the newest version. Yours works too but if you want the durabilty strip working with or without text id recommend downloading the newest version
